# Generated by Django 4.2.1 on 2023-06-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
