# Generated by Django 4.2.1 on 2023-06-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
    ]
