# Generated by Django 4.2.1 on 2023-06-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
