# Generated by Django 4.2.1 on 2023-06-30 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0052_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0010_delete_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_my_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
