# Generated by Django 4.2.1 on 2023-07-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_userorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
