# Generated by Django 4.2.1 on 2023-06-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_tag_rename_created_at_product_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
