# Generated by Django 4.2.1 on 2023-06-08 13:36

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_rename_date_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.category_images_directory_path),
        ),
    ]
