# Generated by Django 4.2.1 on 2023-06-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_category_is_parent_category_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
