# Generated by Django 4.2.1 on 2023-06-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0025_productcharacteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductCharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shopapp.productcharacteristic')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='shopapp.product')),
            ],
        ),
    ]
