# Generated by Django 4.2.1 on 2023-06-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0029_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
