# Generated by Django 4.2.1 on 2023-06-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0030_remove_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
