# Generated by Django 4.2.1 on 2023-06-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0031_rename_name_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='free_delivery',
            new_name='freeDelivery',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
