# Generated by Django 4.2.1 on 2023-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0032_rename_name_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
