# Generated by Django 4.2.1 on 2023-06-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0033_remove_product_rating_product_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate',
            new_name='rating',
        ),
    ]
