# Generated by Django 4.2.1 on 2023-06-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0035_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='rating_count',
        ),
    ]
