# Generated by Django 4.2.1 on 2023-06-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0036_rename_rating_product_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews_count',
        ),
    ]
