# Generated by Django 4.2.1 on 2023-06-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0039_remove_product_rating_count_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shopapp.product')),
                ('salePrice', models.FloatField()),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
            ],
        ),
    ]
