# Generated by Django 4.2.1 on 2023-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0041_product_banner_product_limited_product_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
