# Generated by Django 4.2.1 on 2023-06-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0042_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
