# Generated by Django 4.2.1 on 2023-06-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0045_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
