# Generated by Django 4.2.1 on 2023-06-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0046_remove_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
    ]
