# Generated by Django 4.2.1 on 2023-06-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0049_deliverytype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shopapp.deliverytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paymentType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shopapp.paymenttype'),
            preserve_default=False,
        ),
    ]
