# Generated by Django 4.2.1 on 2023-06-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_delete_userorder'),
        ('shopapp', '0050_order_deliverytype_order_paymenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
