# Generated by Django 4.2.1 on 2023-06-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0052_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
