# Generated by Django 4.2.1 on 2023-06-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0054_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopapp.deliverytype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopapp.paymenttype'),
        ),
    ]
