# Generated by Django 4.2.1 on 2023-06-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0055_alter_order_deliverytype_alter_order_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopapp.orderstatus'),
        ),
    ]
