# Generated by Django 4.2.1 on 2023-07-02 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0059_rename_price_order_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 10, 29, 13, 650334, tzinfo=datetime.timezone.utc)),
        ),
    ]
