# Generated by Django 4.2.1 on 2023-07-02 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0061_alter_order_createdat_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 11, 6, 1, 440894, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 11, 6, 1, 438901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 11, 6, 1, 439898, tzinfo=datetime.timezone.utc)),
        ),
    ]
