# Generated by Django 4.2.1 on 2023-07-02 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0062_alter_order_createdat_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 11, 9, 1, 413044, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 11, 9, 1, 411529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 11, 9, 1, 412040, tzinfo=datetime.timezone.utc)),
        ),
    ]
